//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumSystem.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excursions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Excursions()
        {
            this.ExcursionVisitors = new HashSet<ExcursionVisitors>();
        }
    
        public int ExcursionID { get; set; }
        public Nullable<int> ExhibitionID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public System.DateTime ExcursionDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<int> MaxVisitors { get; set; }
        public Nullable<int> CurrentVisitors { get; set; }
        public string Status { get; set; }
        public string MeetingPoint { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcursionVisitors> ExcursionVisitors { get; set; }
        public virtual Exhibitions Exhibitions { get; set; }
    }
}
