//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumSystem.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcursionVisitors
    {
        public int ExcursionVisitorID { get; set; }
        public Nullable<int> ExcursionID { get; set; }
        public Nullable<int> VisitorID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<bool> Attended { get; set; }
    
        public virtual Excursions Excursions { get; set; }
        public virtual Visitors Visitors { get; set; }
    }
}
