//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumSystem.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExhibitionExponats
    {
        public int ExhibitionExponatID { get; set; }
        public Nullable<int> ExhibitionID { get; set; }
        public Nullable<int> ExponatID { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual Exhibitions Exhibitions { get; set; }
        public virtual Exponats Exponats { get; set; }
    }
}
