//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumSystem.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exponats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exponats()
        {
            this.ExhibitionExponats = new HashSet<ExhibitionExponats>();
        }
    
        public int ExponatID { get; set; }
        public string InventoryNumber { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> YearCreated { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Condition { get; set; }
        public Nullable<bool> Status { get; set; }
        public string PhotoPath { get; set; }
        public string History { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExhibitionExponats> ExhibitionExponats { get; set; }
    }
}
