//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumSystem.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuseumTechDBEntities : DbContext
    {
        public MuseumTechDBEntities()
            : base("name=MuseumTechDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Excursions> Excursions { get; set; }
        public virtual DbSet<ExcursionVisitors> ExcursionVisitors { get; set; }
        public virtual DbSet<ExhibitionExponats> ExhibitionExponats { get; set; }
        public virtual DbSet<Exhibitions> Exhibitions { get; set; }
        public virtual DbSet<Exponats> Exponats { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Visitors> Visitors { get; set; }
        public virtual DbSet<VisitorTypes> VisitorTypes { get; set; }
    }
}
